UC3/Projeto_todo/models/task_model.py
from configurations.database import db

class Task(db.Model):
    __tablename__ = 'tasks'

    id = db.Column(db.Integer, primary_key=True)
    conteudo = db.Column(db.String(200), nullable=False)
    completa = db.Column(db.Boolean, default=False)
    prioridade = db.Column(db.String(50))

    def __repr__(self):
        return f"Tarefa('{self.conteudo}', '{self.completa}', '{self.prioridade}')"

    def __str__(self):
        return f"Conteúdo: {self.conteudo}, Completa: {self.completa}, Prioridade: {self.prioridade}"

    def completar(self):
        self.completa = True

UC3/Projeto_todo/models/user_model.py
from werkzeug.security import generate_password_hash, check_password_hash
from configurations.database import db


class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)
    is_admin = db.Column(db.Boolean, default=False)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f"<User {self.username}>"

UC3/Projeto_todo/app.py
from flask import Flask
from configurations.sql_commands import create_table_tasks, create_table_users, create_root_user
from configurations.database import db
from controllers.task_controller import task_blueprint
from urllib.parse import quote
import os
from dotenv import load_dotenv
from controllers.user_controller import user_blueprint
from models import task_model, user_model

load_dotenv()

app = Flask(__name__)

app.register_blueprint(task_blueprint)
app.register_blueprint(user_blueprint)

user = os.getenv('DB_USER')
password = os.getenv('DB_PASSWORD')
db_name = os.getenv('DB_NAME')
host = os.getenv('DB_HOST')
port = os.getenv('DB_PORT')

password = quote(password)

app.config['SQLALCHEMY_DATABASE_URI'] = f"postgresql://{user}:{password}@{host}:{port}/{db_name}"
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SQLALCHEMY_ECHO'] = True

db.init_app(app)

if __name__ == '__main__':
    create_table_tasks(app, db)
    create_table_users(app, db)
    #create_root_user(app, db)
    app.run(debug=True)

UC3/Projeto_todo/controllers/task_controller.py
from flask import blueprints, render_template, request, url_for, redirect, Blueprint
from services.task_service import TaskService

task_blueprint = Blueprint('task', __name__)
task_service = TaskService()

@task_blueprint.route("/")
def index():
    tarefas = task_service.lista_tarefas()
    return render_template("index.html", tarefas=tarefas)

@task_blueprint.route("/adcionar", methods=["POST"])
def adicionar():
    conteudo = request.form.get("tarefa")
    prioridade = request.form.get("prioridade", "Média")

    if prioridade == '':
        prioridade = 'Média'

    try:
        task_service.adicionar_tarefa(conteudo, prioridade)
    except Exception as e:
        return str(e), 400

    return redirect(url_for("task.index"))

@task_blueprint.route("/completar/<int:tarefa_id>")
def completar(tarefa_id):

    try:
        task_service.completar_tarefa(tarefa_id)
    except Exception as e:
        return str(e), 400

    return redirect(url_for("task.index"))


@task_blueprint.route("/remover/<int:tarefa_id>")
def remover(tarefa_id):
    try:
        task_service.remover_tarefa(tarefa_id)
    except Exception as e:
        return str(e), 400

    return redirect(url_for("task.index"))

UC3/Projeto_todo/controllers/user_controller.py
from flask import Blueprint, render_template, request, url_for, redirect, flash

user_blueprint = Blueprint('user', __name__)

@user_blueprint.route("/adicionar_usuario", methods=['GET', 'POST'])
def criar_usuario():
    flash('Usuário criado')
    return redirect(url_for("task.index"))

UC3/Projeto_todo/templates/form_user.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de usuários</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css) }}">
</head>
<body>
  <h1>Criar novo usuário</h1>
  {% with massagens = get_flashed_messages(with_caregoria=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <p>{{ category }}</p>
      {% endfor %}
    {% endif %}
  {% endwith %}
</body>
</html>

UC3/Projeto_todo/templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Title</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <h1>Lista de Tarefas</h1>

    <form action="{{ url_for('task.adicionar') }}" method="post">
        <input type="text" name="tarefa" placeholder="Nova tarefa." required>
        <input type="text" name="prioridade" placeholder="Prioridade.">
        <button type="submit">Adicionar</button>
    </form>

    <ul>
        {% for tarefa in tarefas %}
        <li>
            {% if tarefa.completa %}
                <del>{{ loop.index }} - {{ tarefa.conteudo }}</del>
            {% else %}
                {{ loop.index }} - {{ tarefa.conteudo }} - {{ tarefa.prioridade }}
            {% endif %}

            {% if tarefa.completa %}
                <a class="remover" href="{{ url_for('task.remover', tarefa_id=tarefa.id) }}">[Remover]</a>
            {% else %}
                <a href="{{ url_for('task.completar', tarefa_id=tarefa.id) }}">[Completar]</a>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
</body>
</html>